import { TextField } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { makeStyles } from "@mui/styles";

const useStyles = makeStyles({
  root: {
    background: "white",

    color: "red",
    height: "180px",
  },
});

export default function Home() {
  const classes = useStyles();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-red-600">hello belal....</h1>
      <TextField
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
        className={classes.root}
        color="primary"
        componentsProps={{ root: { className: "text-red-900 bg-pink-200" } }}
      />
    </div>
  );
}
